### ISSUE TITLE
Retrieving "argv" from main causing plugin freeze

### ISSUE THREAD

**Issue by TheAifam5** [WebFreak001/code-debug#69]
ArchLinux
GNU gdb (GDB) 7.11.1
VS Code Version 1.4.0

The problem is that cannot be seen the string inside of "argv". Debugger loading and loading, but when i want to continue and see other variable, looks like plugin stopped working. 

On Screenshots are more infos.

On this screenshot you see that i put one parameter. This "loading" animation never ends.
![loading](https://cloud.githubusercontent.com/assets/2192274/17466035/f71b7cbc-5d05-11e6-81dc-13713d933c12.png)

On this screenshot you see that "app" variable shows as "nullptr" and that's not true, because "gtk_application_new" allocated the variable.
![allocated](https://cloud.githubusercontent.com/assets/2192274/17466036/f9c77b64-5d05-11e6-877e-9e6ab027bed6.png)

That's logs when i stopped debugging (SHIFT+F5)
```
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
Cannot read property 'body' of null: TypeError: Cannot read property 'body' of null
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:83:4903
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:7573)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:11151)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12979)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12420)
    at i.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:14412)
    at Object.P.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:10230)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12979)
    at i.Class.define._setCompleteValue (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12673)
    at Object.m [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:8135)
Cannot read property 'scopes' of null: TypeError: Cannot read property 'scopes' of null
    at e.getScopes (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:83:6324)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:98:24102
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:7573)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:11151)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12979)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12420)
    at i.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:14412)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:38:13772
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:1364
    at o (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:76)
```

**Comment by WebFreak001** [comment]
The loading issue happens when code-debug receives a type that isn't
implemented yet (the parsing)

I am going to add a debug setting to the launch configuration later today
that will output all GDB messages to the debugger output. The developer
tools don't contain anything important for debugger extensions because the
debugger is actually not a real extension but a separate process.

**Comment by WebFreak001** [comment]
ok I pushed a new version with a debug config flag. Enable `showDevDebugOutput` in your launch.json and then it will output a lot of data to the debug console when pausing. Just send me the line with the argv variable and I will implement these C++ string arrays soon

**Comment by TheAifam5** [comment]
```
GDB -> App: {"token":9,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["variables",[[["name","argc"],["arg","1"],["type","int"],["value","2"]],[["name","argv"],["arg","1"],["type","char **"],["value","0x7fffffffe648"]],[["name","app"],["type","GtkApplication *"],["value","0x0"]],[["name","status"],["type","int"],["value","32767"]]]]]}}
```

**Comment by TheAifam5** [comment]
And what is that error message from Developer Tools log?

```
fake:1 Cannot read property 'body' of null: TypeError: Cannot read property 'body' of null
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:83:4903
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:7573)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:11151)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12979)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12420)
    at i.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:14412)
    at Object.P.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:10230)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12979)
    at i.Class.define._setCompleteValue (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:12673)
    at Object.m [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:32:8135)e.onUnexpectedError @ fake:1
```

**Comment by WebFreak001** [comment]
That error message is vscode having problems with the debug protocol because the debug extension sent some invalid stuff or something. But nothing useful in that error message for me

**Comment by TheAifam5** [comment]
```
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
```
Here is warning that you should use CSS animations  :)

**Comment by WebFreak001** [comment]
Thats not my fault, thats vscode. In fact my extension does not have any control over the UI whatsoever, only when running the command to examine memory. But that one is pure text and no javascript or css or svg

**Comment by WebFreak001** [comment]
I wonder what that `arg:1` value is in the resultRecords.

Also can you try doing `-data-evaluate-expression *0x7fffffffe648`? (replace the `0x7fffffffe648` with the address next to argv)

**Comment by TheAifam5** [comment]
```
-data-evaluate-expression *0x7fffffffe648
{"token":11,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","-5823"]]}}
GDB -> App: {"token":11,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","-5823"]]}}
```

**Comment by WebFreak001** [comment]
Hm so thats the command that lets the code-debug variable expansion hang. Weird that -5823 is hanging it up. Or actually can you also try `-data-evaluate-expression *argv`

But the problem is that this doesnt print the argv array. So unless I find out how to get a string array out of a char** address with `-data-evaluate-expression` or some other MI command it will never be able to correctly display C++ char**

**Comment by TheAifam5** [comment]
```
-data-evaluate-expression *argv
{"token":10,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe941 \"/home/theaifam5/Git/NeoVIM-GTK3/build/neovim-gtk3\""]]}}
GDB -> App: {"token":10,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe941 \"/home/theaifam5/Git/NeoVIM-GTK3/build/neovim-gtk3\""]]}}
```

**Comment by WebFreak001** [comment]
Ah ok thats helping and should be easy to implement. I will do that tomorrow, cleaning up my other projects right now

**Comment by TheAifam5** [comment]
Second parameter:

```
-data-evaluate-expression *(argv+1)
{"token":26,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe973 \"lolaa\""]]}}
GDB -> App: {"token":26,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe973 \"lolaa\""]]}}
```

**Comment by WebFreak001** [comment]
oh nice, and what happens if you do *(argv+2) with only 1 parameter now?

**Comment by TheAifam5** [comment]
argv+2 is NULL..

**Comment by WebFreak001** [comment]
ok so I can just count up until its null and display that then

**Comment by TheAifam5** [comment]
```
-data-evaluate-expression *(argv+1)
{"token":10,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe94b \"firstParameter\""]]}}
GDB -> App: {"token":10,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe94b \"firstParameter\""]]}}
-data-evaluate-expression *(argv+2)
{"token":11,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe95a \"secondParameter\""]]}}
GDB -> App: {"token":11,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe95a \"secondParameter\""]]}}
-data-evaluate-expression *(argv+3)
{"token":12,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe96a \"thirdParameter\""]]}}
GDB -> App: {"token":12,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x7fffffffe96a \"thirdParameter\""]]}}
-data-evaluate-expression *(argv+4)
{"token":13,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x0"]]}}
GDB -> App: {"token":13,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["value","0x0"]]}}
```

**Comment by TheAifam5** [comment]
Its like:
0. StartupPath
1. First param
2. Second param
3. NULL (like separator?)
4. Environment variables.... (very long list)

**Comment by WebFreak001** [comment]
hm there is that `arg: 1` value which is probably indicating that this is an arguments list. So I guess when its not an arguments list it will only do that until null and otherwise also include the environment variables

**Comment by TheAifam5** [comment]
Yep.
Because:
int argc, char **argv, char** envp

**Comment by TheAifam5** [comment]
There is other problem. Because main arguments can be renamed.
argc as argumentCount
argv as argumentList
envp as environmentList

And using "-data-evaluate-expression *(argv+2)" will doesnt work.

**Comment by WebFreak001** [comment]
thats why I will only do that when gdb tells me `arg: 1`

Otherwise it will do the same but stop on the first null and not on the second

**Comment by WebFreak001** [comment]
Sorry been busy lately, trying to implement and push it today (during the next few hours) though

**Comment by WebFreak001** [comment]
So far I've been able to fix basic C-strings but not yet arrays or the args list

**Comment by xiaoyun94** [comment]
bad modify， struct pointer as func param display badlly

<img width="209" height="39" alt="Image" src="https://github.com/user-attachments/assets/41767012-df74-4625-9828-dbc26ff41e89" />

```c
int multi(S1 *s, S1 **d)
{

    return s->x * s->y;
}
```
